sonar.projectKey=fastapi-realworld
sonar.projectName=FastAPI RealWorld Example App
sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc
